version: '2'

services:
  webapp:
    image: jenkins
    restart: always
    network_mode: "host"
    logging:
      driver: json-file
    environment:
      JAVA_OPTS: |-
        -XX:+ParallelRefProcEnabled
        -XX:+ExplicitGCInvokesConcurrent
        -XX:MaxMetaspaceExpansion=64M
        -XX:MaxMetaspaceExpansion=16M
    volumes:
      - /opt/jenkins-data:/var/jenkins_home

  registry: 
    image: registry
    restart: always
    network_mode: "host"
    logging:
      driver: json-file
